name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and Push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./docker/Dockerfile.user
    #     push: true
    #     tags: rohan9823/paytm:latest  # Replace with your Docker Hub username and repository

    # - name: Verify Pushed Image
    #   run: docker pull rohan9823/paytm:latest  # Replace with your Docker Hub username and repository
    - name: Enable SSH RSA algo
      run: echo "CASignatureAlgorithms +ssh-rsa" | sudo tee -a /etc/ssh/sshd_config

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-14-51-200.us-east-2.compute.amazonaws.com
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.NEWSSH }}
        script: |
          sudo docker pull rohan9823/paytm:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name web-app -p 3005:3000 rohan9823/paytm:latest

